name: SLSA Source VSA Creator

description: Creates SLSA Source Track VSAs

runs:
  using: "Composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - id: setup
      run: mkdir -p metadata
      shell: bash
    - id: determine_level
      run: |
        echo "source_level=$(go run github.com/slsa-framework/slsa-source-poc/sourcetool@922b9965dae9c3e8c9e2c5a5f30c720a4fe11354 checklevel --commit ${{ github.sha }} --owner ${{ github.repository_owner }} --repo ${{ github.event.repository.name }} --branch ${{ github.ref_name }} --output_unsigned_vsa ${{ github.workspace }}/metadata/unsigned_vsa.json)" >> $GITHUB_OUTPUT
      shell: bash
    - id: summary
      run: |
        echo "## Unsigned VSA" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/metadata/unsigned_vsa.json >> $GITHUB_STEP_SUMMARY
      shell: bash
    - id: install_witness
      # This is a bit of a hack, running witness happens to also install it.
      # We don't care much about what it does here, we just want the side-effect of witness being installed.
      # If this works well we might lodge some feature requests?
      uses: testifysec/witness-run-action@reusable-workflow
      with:
        command: /bin/sh -c "echo \"hello from slsa-source-poc\""
        step: "install_witness"
    - id: sign_vsa
      # Use witness to sign that VSA...
      run: |
        witness sign -f ${{ github.workspace }}/metadata/unsigned_vsa.json -t "application/vnd.in-toto+json" -o ${{ github.workspace }}/metadata/signed_vsa.json \
        --signer-fulcio-url https://fulcio.sigstore.dev \
        --signer-fulcio-oidc-client-id sigstore \
        --signer-fulcio-oidc-issuer https://oauth2.sigstore.dev/auth \
        --timestamp-servers https://freetsa.org/tsr
        echo "## Signed VSA" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/metadata/signed_vsa.json >> $GITHUB_STEP_SUMMARY
      shell: bash
    - uses: slsa-framework/slsa-source-poc/actions/store_note@main
      with:
        path: ${{ github.workspace }}/metadata/signed_vsa.json
    - uses: slsa-framework/slsa-source-poc/actions/get_note@main
      with:
        commit: ${{ github.event.before }}
        path: ${{ github.workspace }}/metadata/previous_note.json
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: vsa_metadata
        path: ./metadata/
