name: SLSA Source VSA Creator

description: Creates SLSA Source Track VSAs

runs:
  using: "Composite"
  steps:
    - uses: actions/checkout@v4
    - id: determine_level
      run: echo "source_level=$(./determine_source_level.sh ${{ github.sha }} https://github.com/${{ github.repository }} ${{ github.ref }})\n" >> $GITHUB_OUTPUT
    - id: create_vsa
      # Run the script from the action directory so it has access to the template...
      run: |
        mkdir -p metadata
        cd ${{ github.action_path }}
        ./create_vsa.sh ${{ github.sha }} https://github.com/${{ github.repository }} ${{ github.ref }} ${{ steps.determine_level.outputs.source_level }} > ${{ github.workspace }}/metadata/unsigned_vsa.json
      shell: bash
    - id: summary
      run: |
        cat ${{ github.workspace }}/metadata/unsigned_vsa.json >> $GITHUB_STEP_SUMMARY
      shell: bash
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: vsa_metadata
        path: ./metadata/
