name: SLSA Source VSA Creator

description: Creates SLSA Source Track VSAs

runs:
  using: "Composite"
  steps:
    - uses: actions/checkout@v4
    - id: create_vsa
      # Run the script from the action directory so it has access to the template...
      run: |
        cd ${{ github.action_path }}
        ./create_vsa.sh ${{ github.sha }} https://github.com/${{ github.repository }} ${{ github.ref }}  > ${{ github.workspace }}/unsigned_vsa.json
      shell: bash
    - id: summary
      run: |
        echo "```" >> $GITHUB_SUMMARY
        cat unsigned_vsa.json | jq >> $GITHUB_SUMMARY
        echo "```" >> $GITHUB_SUMMARY
      shell: bash
