name: SLSA Source Provenance Creator

description: Creates SLSA Source Track Provenance

runs:
  using: "Composite"
  steps:
    # This PoC depends on creating and checking information when branches are updated (e.g. via push).
    # Don't allow runs that do not occur during pushes.
    - id: check_push
      if: ${{ github.event_name != 'push' }}
      run: |
        echo "This action can only be run during a push."
        exit 1
      shell: bash
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: |
          sourcetool/go.sum
    - id: setup
      run: mkdir -p metadata
      shell: bash
    - uses: slsa-framework/slsa-source-poc/actions/get_note@main
      with:
        commit: ${{ github.event.before }}
        path: ${{ github.workspace }}/metadata/prev_bundle.intoto.jsonl
    - id: determine_level
      run: |
        go run github.com/slsa-framework/slsa-source-poc/sourcetool@bb04ad4308b90bda0e48fa1519d5dea07e441ceb checklevelprov --prev_bundle_path ${{ github.workspace }}/metadata/prev_bundle.intoto.jsonl --commit ${{ github.sha }} --prev_commit ${{ github.event.before }} --owner ${{ github.repository_owner }} --repo ${{ github.event.repository.name }} --branch ${{ github.ref_name }} --output_signed_bundle ${{ github.workspace }}/metadata/signed_bundle.intoto.jsonl
      shell: bash
    - id: summary
      run: |
        echo "## Signed Bundle" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/metadata/signed_bundle.intoto.jsonl >> $GITHUB_STEP_SUMMARY
      shell: bash
    - uses: slsa-framework/slsa-source-poc/actions/store_note@main
      with:
        path: ${{ github.workspace }}/metadata/signed_bundle.intoto.jsonl
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: prov_metadata
        path: ./metadata/
