name: SLSA Source Provenance Creator

description: Creates SLSA Source Track Provenance

runs:
  using: "Composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: |
          sourcetool/go.sum
    - id: setup
      run: mkdir -p metadata
      shell: bash
    - uses: slsa-framework/slsa-source-poc/actions/get_note@main
      with:
        commit: ${{ github.event.before }}
        path: ${{ github.workspace }}/metadata/prev_bundle.intoto.jsonl
    - id: determine_level
      run: |
        go run github.com/slsa-framework/slsa-source-poc/sourcetool@959d6496508cea449f2b7592d132e3cb264d776b checklevelprov --prev_bundle_path ${{ github.workspace }}/metadata/prev_bundle.intoto.jsonl --commit ${{ github.sha }} --prev_commit ${{ github.event.before }} --owner ${{ github.repository_owner }} --repo ${{ github.event.repository.name }} --branch ${{ github.ref_name }} --output_signed_bundle ${{ github.workspace }}/metadata/signed_bundle.intoto.jsonl
      shell: bash
    - id: summary
      run: |
        echo "## Signed Bundle" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/metadata/signed_bundle.intoto.jsonl >> $GITHUB_STEP_SUMMARY
      shell: bash
    - uses: slsa-framework/slsa-source-poc/actions/store_note@main
      with:
        path: ${{ github.workspace }}/metadata/signed_bundle.intoto.jsonl
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: prov_metadata
        path: ./metadata/
