name: SLSA Source Provenance Creator

description: Creates SLSA Source Track Provenance

runs:
  using: "Composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - id: setup
      run: mkdir -p metadata
      shell: bash
    - uses: slsa-framework/slsa-source-poc/actions/get_note@main
      with:
        commit: ${{ github.event.before }}
        path: ${{ github.workspace }}/metadata/prev_bundle.intoto.jsonl
    - id: determine_level
      run: |
        go run github.com/slsa-framework/slsa-source-poc/sourcetool@9db86884defc341b81cda6099e72e1d6ccc0d701 prov --prev_att_path ${{ github.workspace }}/metadata/prev_bundle.intoto.jsonl --commit ${{ github.sha }} --prev_commit ${{ github.event.before }} --owner ${{ github.repository_owner }} --repo ${{ github.event.repository.name }} --branch ${{ github.ref_name }} >> ${{ github.workspace }}/metadata/unsigned_prov.json
      shell: bash
    - id: summary
      run: |
        echo "## Unsigned Provenance" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/metadata/unsigned_prov.json >> $GITHUB_STEP_SUMMARY
      shell: bash
    - id: install_witness
      # This is a bit of a hack, running witness happens to also install it.
      # We don't care much about what it does here, we just want the side-effect of witness being installed.
      # If this works well we might lodge some feature requests?
      uses: testifysec/witness-run-action@reusable-workflow
      with:
        command: /bin/sh -c "echo \"hello from slsa-source-poc\""
        step: "install_witness"
    - id: sign_prov
      # Use witness to sign that provenance...
      run: |
        witness sign -f ${{ github.workspace }}/metadata/unsigned_prov.json -t "application/vnd.in-toto+json" -o ${{ github.workspace }}/metadata/signed_prov.json \
        --signer-fulcio-url https://fulcio.sigstore.dev \
        --signer-fulcio-oidc-client-id sigstore \
        --signer-fulcio-oidc-issuer https://oauth2.sigstore.dev/auth \
        --timestamp-servers https://freetsa.org/tsr
        echo "## Signed Prov" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/metadata/signed_prov.json >> $GITHUB_STEP_SUMMARY
      shell: bash
    - uses: slsa-framework/slsa-source-poc/actions/store_note@main
      with:
        path: ${{ github.workspace }}/metadata/signed_prov.json
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: prov_metadata
        path: ./metadata/
