name: "Computes the SLSA source information"

on:
  workflow_call:

jobs:
  compute_slsa_source:
    permissions:
      contents: write # needed for storing the vsa in the repo
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: prov
      uses: slsa-framework/slsa-source-poc/actions/slsa_with_provenance@main
