name: Attest to this repo's source
on:
  push:
    branches: [ "main" ]
  # TODO: Remove, this should not work.
  workflow_dispatch:

jobs:
  # Whenever new source is pushed or a PR is received, create a new vsa
  check-change:
    permissions:
      contents: write # needed for storing the vsa in the repo.
      id-token: write
    uses: slsa-framework/slsa-source-poc/.github/workflows/create_slsa_source_vsa.yml@main
